### ISSUE TITLE
Prediction not possible on Windows machines due to cuda error

### ISSUE THREAD

**Issue by Maddonix** [matjesg/deepflash2#10]
During prediction on a windows machine a a OS Error occurs due to: 

"RuntimeError: cuda runtime error (801) : operation not supported at ..\torch/csrc/generic/StorageSharing.cpp:247"

Problem: Storage sharing currently not supported on windows.

Proposed solution: Ensemble learner takes "num_workers" argument and passes it to subsequent functions. If num_workers == 0, prediction works for me.

**Comment by matjesg** [comment]
Thanks for bringing this up!

You can now pass keyword arguments to the Ensemble Learner, e.g., 
> EnsembleLearner(files=files, label_fn=label_fn, path=path, dl_kwargs={'num_workers':0})

The `dl_kwargs` are used for contonstructing the dataloaders (see https://docs.fast.ai/data.load.html#DataLoader)
