### ISSUE TITLE
Groundtruth calculation is broken since update of simpleITK

### ISSUE THREAD

**Issue by AmSchulte** [matjesg/deepflash2#3]
The calculation of the ground truth is broken since the release of simpleITK 2.0 

Solution is to add "!pip install SimpleITK==1.2.4" manually to the google colab.
Maybe it would be good to add a requirements.txt to the installation and add an upper version bound to the installed dependencies.

**Comment by matjesg** [comment]
Thanks for bringing up the issue @AmSchulte , i hope it is solved this way!

> requirements.txt to the installation and add an upper version bound to the installed dependencies.

SimpleITK is not part of the requirements of deepflash2 anymore. Only the ground truth estimation notebook uses and installs SimpleITK==1.2.4 if required
