### ISSUE TITLE
Unable to open CSV file link in paper/figures_tables.ipynb

### ISSUE THREAD

**Issue by BubbleDirk** [matjesg/deepflash2#48]
Hi,

I would like to express my gratitude for the great work you have done on your repository. It has been a valuable resource for me and many others. 

I wanted to report an issue with the "paper/figures_tables.ipynb" notebook in your repository. Specifically, I was trying to access the CSV file linked in one of the cells, but unfortunately, the link (**https://github.com/matjesg/deepflash2/releases/tag/paper_source_files**) seems to be broken.

I've checked the link several times to make sure it's typed correctly, but it doesn't seem to work. Could you please take a look and see if there's anything that needs to be fixed on my end? If you could provide an updated link or alternative way to access the data, that would be greatly appreciated.

Thank you for your attention to this matter.

Best regards,
Lee

**Comment by matjesg** [comment]
Hi @BubbleDirk, 

Thanks for bringing up this issue. The correct link is https://github.com/matjesg/deepflash2/releases/tag/paper_source_data. I fixed the link in the notebook. 

Best,
Matthias
