### ISSUE TITLE
Type Error when starting training

### ISSUE THREAD

**Issue by AmSchulte** [matjesg/deepflash2#5]
When I try to start the training process in google colab, this error occurs:

**TypeError: no implementation found for 'torch.nn.functional.cross_entropy' on types that implement __torch_function__: [<class 'fastai.torch_core.TensorImage'>, <class 'fastai.torch_core.TensorMask'>]**

as well as 

**FileNotFoundError: [Errno 2] No such file or directory: 'models/model.pth'**

in the end.

Hope you know whats the problem.

**Comment by matjesg** [comment]
Thx
