### ISSUE TITLE
Instance Segmentation Training 

### ISSUE THREAD

**Issue by pakiessling** [matjesg/deepflash2#52]
Hi there, thank you for the tool. Excited to try it out.

I would like to use deepflash2 for instance segmentation.
I have masks that look like this:

![grafik](https://github.com/matjesg/deepflash2/assets/104848590/5697f100-3489-4f18-a3b7-ca1a01bff0f6)

So far I have been using Cellpose.
Do you think deepflash2 would be superior, or is it more focused on semantic segmentation?
Do I have to convert my masks to binary foreground / background masks to train deepflash2?

**Comment by matjesg** [comment]
Hi @pakiessling 
deepflash2 can generally be used for similar use cases as cellpose -- it also uses cellpose in the background for instance segmentation, as described in our [paper](https://www.nature.com/articles/s41467-023-36960-9).

The instance segmentation masks are expected to have 0 as background and integers starting from 1 for each instance. Here are some examples how to convert the masks for some public datasets ([conic](https://github.com/matjesg/deepflash2/blob/master/paper/challenge_data/preprocess_conic.ipynb), [monuseg](https://github.com/matjesg/deepflash2/blob/master/paper/challenge_data/preprocess_monuseg.ipynb)).
