### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by zhangqioct** [matjesg/deepflash2#53]
Hi there, thank you for the tool. Excited to try it out.

When I was running validation, there was an error “local variable 'df_val' referenced before assignment”. Can you help me solve it? Thank you!

**Comment by matjesg** [comment]
Hi @zhangqioct , the error sometimes occurs when the data correctly loaded or the models are not trained properly. There is also a complete error log available at ~/.deepflash2/logs -- feel free to post it here!

**Comment by zhangqioct** [comment]
Hi, thank you very much for your reply! We have resolved the issue!
